name: 
on: [push]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and run an app
      working-directory: ./backend
      run: |
        python -m venv .env
        source .env/bin/activate
        pip install --upgrade pip
        pip install poetry
        poetry install
        fastapi src/anime/run.py